// go run mkasm.go darwin amd64
// Code generated by the command above; DO NOT EDIT.

#include "textflag.h"

TEXT proc_pidinfo_trampoline<>(SB),NOSPLIT,$0-0
	JMP	proc_pidinfo(SB)
GLOBL	·proc_pidinfo_trampoline_addr(SB), RODATA, $8
DATA	·proc_pidinfo_trampoline_addr(SB)/8, $proc_pidinfo_trampoline<>(SB)
