linters:
  disable-all: true
  enable:
    - gofumpt
    - staticcheck
    - govet
    - gci

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/abyss219/mihomo)
      - default
  staticcheck:
    go: '1.19'
