version: "2"
linters:
  default: none
  enable:
    - staticcheck
    - govet

formatters:
  enable:
    - gofumpt
    - gci
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(github.com/metacubex/mihomo)
        - default
