package openvpn

import (
	"bytes"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"net"
	"strconv"
	"strings"
	"time"
)

const (
	ProtoUDP = "udp"
	ProtoTCP = "tcp"

	CipherAES128GCM        = "AES-128-GCM"
	CipherAES192GCM        = "AES-192-GCM"
	CipherAES256GCM        = "AES-256-GCM"
	CipherAESCBC           = "AES-CBC"
	CipherAES128CBC        = "AES-128-CBC"
	CipherAES192CBC        = "AES-192-CBC"
	CipherAES256CBC        = "AES-256-CBC"
	CipherChaCha20Poly1305 = "CHACHA20-POLY1305"
	AuthMD5                = "MD5"
	AuthSHA1               = "SHA1"
	AuthSHA256             = "SHA256"
	AuthSHA384             = "SHA384"
	AuthSHA512             = "SHA512"

	CompLzoYes = "yes"
)

// ClientConfig is the normalized subset generated by hwdsl2/openvpn-install.
type ClientConfig struct {
	RemoteHost string
	RemotePort uint16
	Proto      string
	Dev        string
	Cipher     string
	Auth       string
	CompLZO    string

	// Compression is the OpenVPN "compress" directive mode (none/stub/stub-v2/lz4/lz4-v2).
	Compression string
	// AllowCompression controls the compression policy (no/asym/yes).
	AllowCompression string

	// TLS verification options (matching OpenVPN remote-cert-tls etc.)

	// ServerName is the expected server certificate name.
	ServerName string
	// ServerNameType is the type of name verification: "subject", "name", or "name-prefix".
	ServerNameType string
	// PeerFingerprint is a list of allowed SHA-256 fingerprints (hex, lowercase, 64 chars).
	PeerFingerprint []string
	// RemoteCertKU is a list of required key usage masks (hex strings).
	RemoteCertKU []string
	// RemoteCertEKU is the required extended key usage: "server" or "client".
	RemoteCertEKU string
	// TLSVersionMin is the minimum TLS version ("1.0", "1.1", "1.2", "1.3").
	TLSVersionMin string
	// TLSVersionMax is the maximum TLS version.
	TLSVersionMax string
	// TLSCipher is a colon-separated list of OpenSSL cipher suite names.
	TLSCipher string
	// TLSGroups is a colon-separated list of TLS key exchange groups.
	TLSGroups string

	CA       []byte
	Cert     []byte
	Key      []byte
	TLSAuth  []byte
	TLSCrypt []byte

	KeyDirection string

	Username string
	Password string

	PeerInfo map[string]string

	PingInterval time.Duration
	PingRestart  time.Duration

	TLSCryptKey []byte
	TLSAuthKey  []byte

	// TLSCryptV2ClientKey is the client-side key for tls-crypt-v2 (256 bytes).
	TLSCryptV2ClientKey []byte
	// TLSCryptV2ServerKey is the server-side key for tls-crypt-v2 (256 bytes).
	TLSCryptV2ServerKey []byte

	// TLSCryptV2Client is the raw PEM-encoded tls-crypt-v2 client key.
	TLSCryptV2Client []byte
	// TLSCryptV2Server is the raw PEM-encoded tls-crypt-v2 server key.
	TLSCryptV2Server []byte

	// DataCiphers is the list of data channel ciphers the client offers to
	// the server for negotiation (OpenVPN --data-ciphers). If non-empty, the
	// negotiated cipher is the first entry in the server's pushed cipher list
	// that also appears here. If empty, the single Cipher field is used.
	DataCiphers []string

	// FallbackCipher is used when the server does not support cipher
	// negotiation (OpenVPN --data-ciphers-fallback).
	FallbackCipher string
}

// DataCipherKeyLength returns the key size for the negotiated data cipher.
func (c ClientConfig) DataCipherKeyLength() int {
	return CipherKeyLength(c.Cipher)
}

// CipherKeyLength returns the key size for a given cipher name.
func CipherKeyLength(cipher string) int {
	switch cipher {
	case CipherAES256GCM, CipherAES256CBC, CipherChaCha20Poly1305:
		return 32
	case CipherAES192GCM, CipherAES192CBC:
		return 24
	default:
		return 16
	}
}

// NegotiateCipher selects the data channel cipher based on the server-pushed
// cipher list and the locally configured DataCiphers list.
//
// If the server pushed a cipher list (via "data-ciphers" or "cipher" push
// options), the result is the first cipher in the server's list that also
// appears in the local DataCiphers list. If no intersection exists and a
// FallbackCipher is configured, it is used. If no fallback is configured but
// the server pushed a single cipher that matches the local Cipher, that is
// used.
//
// If the server did not push any cipher options, the local Cipher is used
// as-is (legacy behavior for servers without cipher negotiation).
func (c ClientConfig) NegotiateCipher(pushedCiphers []string, pushedCipher string) (string, error) {
	if len(pushedCiphers) == 0 && pushedCipher == "" {
		// Server did not negotiate; use the configured cipher.
		return c.Cipher, nil
	}

	if len(c.DataCiphers) > 0 {
		// Try to find a cipher in the server's list that we also support.
		serverList := pushedCiphers
		if len(serverList) == 0 && pushedCipher != "" {
			serverList = []string{pushedCipher}
		}
		for _, serverCipher := range serverList {
			normalized := normalizeCipher(serverCipher)
			for _, localCipher := range c.DataCiphers {
				if normalizeCipher(localCipher) == normalized {
					return normalized, nil
				}
			}
		}
		// No intersection. Try fallback.
		if c.FallbackCipher != "" {
			return normalizeCipher(c.FallbackCipher), nil
		}
		return "", fmt.Errorf("no common data cipher between client %v and server %v", c.DataCiphers, serverList)
	}

	// No local DataCiphers list. Use the pushed cipher if it matches our
	// configured cipher, or if we have a fallback.
	if pushedCipher != "" {
		normalized := normalizeCipher(pushedCipher)
		if normalized == c.Cipher {
			return normalized, nil
		}
		if c.FallbackCipher != "" {
			return normalizeCipher(c.FallbackCipher), nil
		}
		// Accept the server's cipher even if it differs from our default,
		// as long as it's a supported cipher.
		if isSupportedCipher(normalized) {
			return normalized, nil
		}
		return "", fmt.Errorf("server pushed unsupported cipher %q", pushedCipher)
	}

	// Server pushed a data-ciphers list but no single cipher.
	if len(pushedCiphers) > 0 {
		for _, sc := range pushedCiphers {
			normalized := normalizeCipher(sc)
			if isSupportedCipher(normalized) {
				if c.FallbackCipher != "" {
					return normalizeCipher(c.FallbackCipher), nil
				}
				return normalized, nil
			}
		}
	}

	return c.Cipher, nil
}

// isSupportedCipher returns true if the cipher name is recognized.
func isSupportedCipher(cipher string) bool {
	switch cipher {
	case CipherAES128GCM, CipherAES192GCM, CipherAES256GCM,
		CipherAES128CBC, CipherAES192CBC, CipherAES256CBC,
		CipherChaCha20Poly1305:
		return true
	default:
		return false
	}
}

// buildCompressor creates a Compressor from the config's compression settings.
// Returns nil if no compression framing is configured.
func (c ClientConfig) buildCompressor() *Compressor {
	// Priority: compress directive > comp-lzo.
	if c.Compression != "" && c.Compression != "off" && c.Compression != "disabled" && c.Compression != "none" {
		mode, err := ParseCompressionMode(c.Compression)
		if err != nil {
			return nil
		}
		if mode == CompressionNone {
			return nil
		}
		policy, _ := ParseAllowCompression(c.AllowCompression)
		return NewCompressor(mode, policy)
	}

	// Legacy comp-lzo.
	if c.CompLZO == CompLzoYes {
		policy, _ := ParseAllowCompression(c.AllowCompression)
		// If allow-compression is explicitly "no", don't create a compressor.
		if policy == AllowCompressionNo && c.AllowCompression != "" {
			return nil
		}
		return NewCompressor(CompressionLZO, AllowCompressionYes)
	}

	return nil
}

func (c ClientConfig) RemoteAddress() string {
	return net.JoinHostPort(c.RemoteHost, strconv.Itoa(int(c.RemotePort)))
}

func normalizeProto(proto string) string {
	switch strings.ToLower(strings.TrimSpace(proto)) {
	case "":
		return ProtoUDP
	case "udp", "udp4":
		return ProtoUDP
	case "tcp", "tcp-client", "tcp4", "tcp4-client":
		return ProtoTCP
	default:
		return strings.ToLower(strings.TrimSpace(proto))
	}
}

func normalizeCipher(cipher string) string {
	switch strings.ToUpper(strings.TrimSpace(cipher)) {
	case "":
		return CipherAES128GCM
	case CipherAESCBC:
		return CipherAES128CBC
	default:
		return strings.ToUpper(strings.TrimSpace(cipher))
	}
}

func normalizeAuth(auth string) string {
	switch strings.ToUpper(strings.TrimSpace(auth)) {
	case "":
		return AuthSHA256
	case "SHA-1":
		return AuthSHA1
	default:
		return strings.ToUpper(strings.TrimSpace(auth))
	}
}

func normalizeCompLZO(compLZO string) string {
	switch strings.ToLower(strings.TrimSpace(compLZO)) {
	case "yes", "adaptive":
		return CompLzoYes
	default:
		return strings.ToLower(strings.TrimSpace(compLZO))
	}
}

func (c *ClientConfig) Prepare() error {
	if c == nil {
		return errors.New("nil openvpn client config")
	}
	c.RemoteHost = strings.TrimSpace(c.RemoteHost)
	c.Proto = normalizeProto(c.Proto)
	if c.Dev == "" {
		c.Dev = "tun"
	}
	c.Dev = strings.ToLower(strings.TrimSpace(c.Dev))
	c.Cipher = normalizeCipher(c.Cipher)
	c.Auth = normalizeAuth(c.Auth)
	c.CompLZO = normalizeCompLZO(c.CompLZO)
	c.Compression = normalizeLower(c.Compression)
	c.AllowCompression = normalizeLower(c.AllowCompression)

	if err := c.ValidateInstallScriptSubset(); err != nil {
		return err
	}
	if len(bytes.TrimSpace(c.TLSAuth)) > 0 {
		key, err := DecodeStaticKey(c.TLSAuth)
		if err != nil {
			return fmt.Errorf("parse tls-auth key: %w", err)
		}
		c.TLSAuthKey = key
	}
	if len(bytes.TrimSpace(c.TLSCrypt)) > 0 {
		key, err := DecodeStaticKey(c.TLSCrypt)
		if err != nil {
			return fmt.Errorf("parse tls-crypt key: %w", err)
		}
		c.TLSCryptKey = key
	}
	if len(bytes.TrimSpace(c.TLSCryptV2Client)) > 0 {
		key, err := DecodeTLSCryptV2ClientKey(c.TLSCryptV2Client)
		if err != nil {
			return fmt.Errorf("parse tls-crypt-v2 client key: %w", err)
		}
		c.TLSCryptV2ClientKey = key
	}
	if len(bytes.TrimSpace(c.TLSCryptV2Server)) > 0 {
		key, err := DecodeTLSCryptV2ServerKey(c.TLSCryptV2Server)
		if err != nil {
			return fmt.Errorf("parse tls-crypt-v2 server key: %w", err)
		}
		c.TLSCryptV2ServerKey = key
	}
	return nil
}

func (c *ClientConfig) ValidateInstallScriptSubset() error {
	if c == nil {
		return errors.New("nil openvpn client config")
	}
	if c.RemoteHost == "" || c.RemotePort == 0 {
		return errors.New("openvpn config requires remote host and port")
	}
	if c.Dev != "tun" {
		return fmt.Errorf("unsupported openvpn dev %q: only dev tun is supported", c.Dev)
	}
	if c.Proto != ProtoUDP && c.Proto != ProtoTCP {
		return fmt.Errorf("unsupported openvpn proto %q: only udp and tcp are supported", c.Proto)
	}
	if c.Cipher != CipherAES128GCM && c.Cipher != CipherAES192GCM && c.Cipher != CipherAES256GCM && c.Cipher != CipherAES128CBC && c.Cipher != CipherAES192CBC && c.Cipher != CipherAES256CBC && c.Cipher != CipherChaCha20Poly1305 {
		return fmt.Errorf("unsupported openvpn cipher %q: only %s, %s, %s, %s, %s, %s and %s are supported", c.Cipher, CipherAES128GCM, CipherAES192GCM, CipherAES256GCM, CipherAES128CBC, CipherAES192CBC, CipherAES256CBC, CipherChaCha20Poly1305)
	}
	if c.Auth != AuthMD5 && c.Auth != AuthSHA1 && c.Auth != AuthSHA256 && c.Auth != AuthSHA384 && c.Auth != AuthSHA512 {
		return fmt.Errorf("unsupported openvpn auth %q: only %s, %s, %s, %s and %s are supported", c.Auth, AuthMD5, AuthSHA1, AuthSHA256, AuthSHA384, AuthSHA512)
	}
	if c.KeyDirection != "1" && c.KeyDirection != "0" && c.KeyDirection != "" {
		return fmt.Errorf("unsupported openvpn key-direction %q: only '1' and '0' are supported", c.KeyDirection)
	}
	if len(bytes.TrimSpace(c.TLSAuth)) > 0 && len(bytes.TrimSpace(c.TLSCrypt)) > 0 {
		return errors.New("openvpn tls-auth and tls-crypt are mutually exclusive")
	}
	hasTLSCryptV2 := len(bytes.TrimSpace(c.TLSCryptV2Client)) > 0 || len(bytes.TrimSpace(c.TLSCryptV2Server)) > 0
	if hasTLSCryptV2 {
		if len(bytes.TrimSpace(c.TLSAuth)) > 0 || len(bytes.TrimSpace(c.TLSCrypt)) > 0 {
			return errors.New("openvpn tls-crypt-v2 is mutually exclusive with tls-auth and tls-crypt")
		}
		if len(bytes.TrimSpace(c.TLSCryptV2Client)) == 0 || len(bytes.TrimSpace(c.TLSCryptV2Server)) == 0 {
			return errors.New("openvpn tls-crypt-v2 requires both client and server keys")
		}
	}
	for name, value := range map[string][]byte{
		"ca": c.CA,
	} {
		if len(bytes.TrimSpace(value)) == 0 {
			return fmt.Errorf("openvpn config requires inline <%s> block", name)
		}
	}
	if block, _ := pem.Decode(c.CA); block == nil {
		return errors.New("inline <ca> block is not PEM")
	}
	hasCert := len(bytes.TrimSpace(c.Cert)) > 0 || len(bytes.TrimSpace(c.Key)) > 0
	if hasCert {
		if len(bytes.TrimSpace(c.Cert)) == 0 || len(bytes.TrimSpace(c.Key)) == 0 {
			return errors.New("openvpn cert and key must both be set when using client certificate auth")
		}
		if block, _ := pem.Decode(c.Cert); block == nil {
			return errors.New("inline <cert> block is not PEM")
		}
		if block, _ := pem.Decode(c.Key); block == nil {
			return errors.New("inline <key> block is not PEM")
		}
	} else if strings.TrimSpace(c.Username) == "" {
		return errors.New("openvpn requires either cert+key or username (auth-user-pass)")
	}
	if c.PingInterval < 0 {
		return errors.New("openvpn ping interval must be positive")
	}
	if c.PingRestart < 0 {
		return errors.New("openvpn ping restart must be positive")
	}
	return nil
}

func DecodeStaticKey(block []byte) ([]byte, error) {
	return decodeStaticKeyWithType(block, "OpenVPN Static key V1")
}

// decodeStaticKeyWithType decodes a static key from a PEM-like block with a
// specified type string (e.g. "OpenVPN Static key V1" or
// "OpenVPN tls-crypt-v2 client key"). The raw key is hex-encoded in the
// block body, matching OpenVPN's key file format.
func decodeStaticKeyWithType(block []byte, keyType string) ([]byte, error) {
	var hexLines []string
	for _, raw := range strings.Split(string(block), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "-----BEGIN ") || strings.HasPrefix(line, "-----END ") {
			continue
		}
		hexLines = append(hexLines, line)
	}
	encoded := strings.Join(hexLines, "")
	key, err := hex.DecodeString(encoded)
	if err != nil {
		return nil, err
	}
	if len(key) != 256 {
		return nil, fmt.Errorf("invalid static key length %d, expected 256 bytes", len(key))
	}
	return key, nil
}
