package openvpn

import (
	"bytes"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"net"
	"strconv"
	"strings"
)

const (
	ProtoUDP = "udp"
	ProtoTCP = "tcp"

	CipherAES128GCM = "AES-128-GCM"
	CipherAES256GCM = "AES-256-GCM"
	AuthSHA256      = "SHA256"
)

// ClientConfig is the normalized subset generated by hwdsl2/openvpn-install.
type ClientConfig struct {
	RemoteHost string
	RemotePort uint16
	Proto      string
	Dev        string
	Cipher     string
	Auth       string

	CA       []byte
	Cert     []byte
	Key      []byte
	TLSCrypt []byte

	Username string
	Password string

	TLSCryptKey []byte
}

// DataCipherKeyLength returns the AES key size for the negotiated data cipher.
func (c ClientConfig) DataCipherKeyLength() int {
	switch c.Cipher {
	case CipherAES256GCM:
		return 32
	default:
		return 16
	}
}

func (c ClientConfig) RemoteAddress() string {
	return net.JoinHostPort(c.RemoteHost, strconv.Itoa(int(c.RemotePort)))
}

func normalizeProto(proto string) string {
	switch strings.ToLower(strings.TrimSpace(proto)) {
	case "":
		return ProtoUDP
	case "udp", "udp4":
		return ProtoUDP
	case "tcp", "tcp-client", "tcp4", "tcp4-client":
		return ProtoTCP
	default:
		return strings.ToLower(strings.TrimSpace(proto))
	}
}

func (c *ClientConfig) Prepare() error {
	if c == nil {
		return errors.New("nil openvpn client config")
	}
	c.RemoteHost = strings.TrimSpace(c.RemoteHost)
	c.Proto = normalizeProto(c.Proto)
	if c.Dev == "" {
		c.Dev = "tun"
	}
	c.Dev = strings.ToLower(strings.TrimSpace(c.Dev))
	if c.Cipher == "" {
		c.Cipher = CipherAES128GCM
	}
	c.Cipher = strings.ToUpper(strings.TrimSpace(c.Cipher))
	if c.Auth == "" {
		c.Auth = AuthSHA256
	}
	c.Auth = strings.ToUpper(strings.TrimSpace(c.Auth))
	if err := c.ValidateInstallScriptSubset(); err != nil {
		return err
	}
	key, err := DecodeStaticKey(c.TLSCrypt)
	if err != nil {
		return fmt.Errorf("parse tls-crypt key: %w", err)
	}
	c.TLSCryptKey = key
	return nil
}

func (c *ClientConfig) ValidateInstallScriptSubset() error {
	if c == nil {
		return errors.New("nil openvpn client config")
	}
	if c.RemoteHost == "" || c.RemotePort == 0 {
		return errors.New("openvpn config requires remote host and port")
	}
	if c.Dev != "tun" {
		return fmt.Errorf("unsupported openvpn dev %q: only dev tun is supported", c.Dev)
	}
	if c.Proto != ProtoUDP && c.Proto != ProtoTCP {
		return fmt.Errorf("unsupported openvpn proto %q: only udp and tcp are supported", c.Proto)
	}
	if c.Cipher != CipherAES128GCM && c.Cipher != CipherAES256GCM {
		return fmt.Errorf("unsupported openvpn cipher %q: only %s and %s are supported", c.Cipher, CipherAES128GCM, CipherAES256GCM)
	}
	if c.Auth != AuthSHA256 {
		return fmt.Errorf("unsupported openvpn auth %q: only %s is supported", c.Auth, AuthSHA256)
	}
	for name, value := range map[string][]byte{
		"ca":        c.CA,
		"tls-crypt": c.TLSCrypt,
	} {
		if len(bytes.TrimSpace(value)) == 0 {
			return fmt.Errorf("openvpn config requires inline <%s> block", name)
		}
	}
	if block, _ := pem.Decode(c.CA); block == nil {
		return errors.New("inline <ca> block is not PEM")
	}
	hasCert := len(bytes.TrimSpace(c.Cert)) > 0 || len(bytes.TrimSpace(c.Key)) > 0
	if hasCert {
		if len(bytes.TrimSpace(c.Cert)) == 0 || len(bytes.TrimSpace(c.Key)) == 0 {
			return errors.New("openvpn cert and key must both be set when using client certificate auth")
		}
		if block, _ := pem.Decode(c.Cert); block == nil {
			return errors.New("inline <cert> block is not PEM")
		}
		if block, _ := pem.Decode(c.Key); block == nil {
			return errors.New("inline <key> block is not PEM")
		}
	} else if strings.TrimSpace(c.Username) == "" {
		return errors.New("openvpn requires either cert+key or username (auth-user-pass)")
	}
	return nil
}

func DecodeStaticKey(block []byte) ([]byte, error) {
	var hexLines []string
	for _, raw := range strings.Split(string(block), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "-----BEGIN OpenVPN Static key") || strings.HasPrefix(line, "-----END OpenVPN Static key") {
			continue
		}
		hexLines = append(hexLines, line)
	}
	encoded := strings.Join(hexLines, "")
	key, err := hex.DecodeString(encoded)
	if err != nil {
		return nil, err
	}
	if len(key) != 256 {
		return nil, fmt.Errorf("invalid static key length %d, expected 256 bytes", len(key))
	}
	return key, nil
}
