// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type datapathDaeParam struct {
	TproxyPort           uint32
	Dae0Ifindex          uint32
	WanIfindex           uint32
	Dae0peerMac          [6]uint8
	UseRedirectPeer      uint8
	ProxyLocal           uint8
	DaeSocketMark        uint32
	ControlPlanePid      uint32
	LocalIp              uint32
	HasProxySrcIps       uint8
	HasProxyDstIps       uint8
	HasProxySrcPorts     uint8
	HasProxyDstPorts     uint8
	DirectOffloadEnabled uint8
	HasProxyProcesses    uint8
	HasBypassProcesses   uint8
	HasBypassDscps       uint8
	HasBypassFwmarks     uint8
	Pad1                 [3]uint8
}

type datapathFlowOwnerEntry struct {
	LastSeenNs uint64
	Owner      uint8
	Pad        [7]uint8
}

type datapathIp6Key struct{ Addr [16]uint8 }

type datapathLpmV4Key struct {
	Prefixlen uint32
	Addr      uint32
}

type datapathLpmV6Key struct {
	Prefixlen uint32
	Addr      [16]uint8
}

type datapathRedirectEntry struct {
	Ifindex uint32
	FromWan uint8
	Pad0    [3]uint8
	Smac    [6]uint8
	Dmac    [6]uint8
}

type datapathRedirectTuple struct {
	SrcIp     [16]uint8
	DstIp     [16]uint8
	SrcPort   uint16
	DstPort   uint16
	Proto     uint8
	IpVersion uint8
	Pad       [2]uint8
}

// loadDatapath returns the embedded CollectionSpec for datapath.
func loadDatapath() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DatapathBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load datapath: %w", err)
	}

	return spec, err
}

// loadDatapathObjects loads datapath and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*datapathObjects
//	*datapathPrograms
//	*datapathMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDatapathObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDatapath()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// datapathSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type datapathSpecs struct {
	datapathProgramSpecs
	datapathMapSpecs
}

// datapathSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type datapathProgramSpecs struct {
	TcDae0Ingress     *ebpf.ProgramSpec `ebpf:"tc_dae0_ingress"`
	TcDae0peerIngress *ebpf.ProgramSpec `ebpf:"tc_dae0peer_ingress"`
	TcLanIngress      *ebpf.ProgramSpec `ebpf:"tc_lan_ingress"`
	TproxySkLookup    *ebpf.ProgramSpec `ebpf:"tproxy_sk_lookup"`
}

// datapathMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type datapathMapSpecs struct {
	BYPASS_DST_IP6S   *ebpf.MapSpec `ebpf:"BYPASS_DST_IP6S"`
	BYPASS_DST_IPS    *ebpf.MapSpec `ebpf:"BYPASS_DST_IPS"`
	BYPASS_DST_PORTS  *ebpf.MapSpec `ebpf:"BYPASS_DST_PORTS"`
	BYPASS_SRC_IP6S   *ebpf.MapSpec `ebpf:"BYPASS_SRC_IP6S"`
	BYPASS_SRC_IPS    *ebpf.MapSpec `ebpf:"BYPASS_SRC_IPS"`
	BYPASS_SRC_PORTS  *ebpf.MapSpec `ebpf:"BYPASS_SRC_PORTS"`
	DAE_PARAM         *ebpf.MapSpec `ebpf:"DAE_PARAM"`
	DYN_DIRECT4       *ebpf.MapSpec `ebpf:"DYN_DIRECT4"`
	DYN_DIRECT6       *ebpf.MapSpec `ebpf:"DYN_DIRECT6"`
	DYN_PROXY4        *ebpf.MapSpec `ebpf:"DYN_PROXY4"`
	DYN_PROXY6        *ebpf.MapSpec `ebpf:"DYN_PROXY6"`
	EVENT_RINGBUF     *ebpf.MapSpec `ebpf:"EVENT_RINGBUF"`
	FLOW_OWNER        *ebpf.MapSpec `ebpf:"FLOW_OWNER"`
	LISTEN_SOCKET_MAP *ebpf.MapSpec `ebpf:"LISTEN_SOCKET_MAP"`
	PROXY_DST_IP6S    *ebpf.MapSpec `ebpf:"PROXY_DST_IP6S"`
	PROXY_DST_IPS     *ebpf.MapSpec `ebpf:"PROXY_DST_IPS"`
	PROXY_DST_PORTS   *ebpf.MapSpec `ebpf:"PROXY_DST_PORTS"`
	PROXY_SRC_IP6S    *ebpf.MapSpec `ebpf:"PROXY_SRC_IP6S"`
	PROXY_SRC_IPS     *ebpf.MapSpec `ebpf:"PROXY_SRC_IPS"`
	PROXY_SRC_PORTS   *ebpf.MapSpec `ebpf:"PROXY_SRC_PORTS"`
	REDIRECT_TRACK    *ebpf.MapSpec `ebpf:"REDIRECT_TRACK"`
}

// datapathObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDatapathObjects or ebpf.CollectionSpec.LoadAndAssign.
type datapathObjects struct {
	datapathPrograms
	datapathMaps
}

func (o *datapathObjects) Close() error {
	return _DatapathClose(
		&o.datapathPrograms,
		&o.datapathMaps,
	)
}

// datapathMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDatapathObjects or ebpf.CollectionSpec.LoadAndAssign.
type datapathMaps struct {
	BYPASS_DST_IP6S   *ebpf.Map `ebpf:"BYPASS_DST_IP6S"`
	BYPASS_DST_IPS    *ebpf.Map `ebpf:"BYPASS_DST_IPS"`
	BYPASS_DST_PORTS  *ebpf.Map `ebpf:"BYPASS_DST_PORTS"`
	BYPASS_SRC_IP6S   *ebpf.Map `ebpf:"BYPASS_SRC_IP6S"`
	BYPASS_SRC_IPS    *ebpf.Map `ebpf:"BYPASS_SRC_IPS"`
	BYPASS_SRC_PORTS  *ebpf.Map `ebpf:"BYPASS_SRC_PORTS"`
	DAE_PARAM         *ebpf.Map `ebpf:"DAE_PARAM"`
	DYN_DIRECT4       *ebpf.Map `ebpf:"DYN_DIRECT4"`
	DYN_DIRECT6       *ebpf.Map `ebpf:"DYN_DIRECT6"`
	DYN_PROXY4        *ebpf.Map `ebpf:"DYN_PROXY4"`
	DYN_PROXY6        *ebpf.Map `ebpf:"DYN_PROXY6"`
	EVENT_RINGBUF     *ebpf.Map `ebpf:"EVENT_RINGBUF"`
	FLOW_OWNER        *ebpf.Map `ebpf:"FLOW_OWNER"`
	LISTEN_SOCKET_MAP *ebpf.Map `ebpf:"LISTEN_SOCKET_MAP"`
	PROXY_DST_IP6S    *ebpf.Map `ebpf:"PROXY_DST_IP6S"`
	PROXY_DST_IPS     *ebpf.Map `ebpf:"PROXY_DST_IPS"`
	PROXY_DST_PORTS   *ebpf.Map `ebpf:"PROXY_DST_PORTS"`
	PROXY_SRC_IP6S    *ebpf.Map `ebpf:"PROXY_SRC_IP6S"`
	PROXY_SRC_IPS     *ebpf.Map `ebpf:"PROXY_SRC_IPS"`
	PROXY_SRC_PORTS   *ebpf.Map `ebpf:"PROXY_SRC_PORTS"`
	REDIRECT_TRACK    *ebpf.Map `ebpf:"REDIRECT_TRACK"`
}

func (m *datapathMaps) Close() error {
	return _DatapathClose(
		m.BYPASS_DST_IP6S,
		m.BYPASS_DST_IPS,
		m.BYPASS_DST_PORTS,
		m.BYPASS_SRC_IP6S,
		m.BYPASS_SRC_IPS,
		m.BYPASS_SRC_PORTS,
		m.DAE_PARAM,
		m.DYN_DIRECT4,
		m.DYN_DIRECT6,
		m.DYN_PROXY4,
		m.DYN_PROXY6,
		m.EVENT_RINGBUF,
		m.FLOW_OWNER,
		m.LISTEN_SOCKET_MAP,
		m.PROXY_DST_IP6S,
		m.PROXY_DST_IPS,
		m.PROXY_DST_PORTS,
		m.PROXY_SRC_IP6S,
		m.PROXY_SRC_IPS,
		m.PROXY_SRC_PORTS,
		m.REDIRECT_TRACK,
	)
}

// datapathPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDatapathObjects or ebpf.CollectionSpec.LoadAndAssign.
type datapathPrograms struct {
	TcDae0Ingress     *ebpf.Program `ebpf:"tc_dae0_ingress"`
	TcDae0peerIngress *ebpf.Program `ebpf:"tc_dae0peer_ingress"`
	TcLanIngress      *ebpf.Program `ebpf:"tc_lan_ingress"`
	TproxySkLookup    *ebpf.Program `ebpf:"tproxy_sk_lookup"`
}

func (p *datapathPrograms) Close() error {
	return _DatapathClose(
		p.TcDae0Ingress,
		p.TcDae0peerIngress,
		p.TcLanIngress,
		p.TproxySkLookup,
	)
}

func _DatapathClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed datapath_bpfel.o
var _DatapathBytes []byte
